a = int(input("Enter a number: "))
e = int(input("Enter another number: "))
print("Sum:", a + e)
print("Difference:", a - e)
print("Product:", a * e)
print("Quotient:", a / e)
print("Floor Division:", a // e)
print("Remainder:", a % e)
print("Exponentiation:", a ** e)